// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuksConnectAPI.Data;

#nullable disable

namespace TuksConnectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407181833_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TuksConnectAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventTitle = "AI & Tech Trends Workshop",
                            Location = "Merensky II Library",
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 2,
                            EventTitle = "Tuks Music Festival",
                            Location = "Amphitheatre",
                            TicketPrice = 250m
                        },
                        new
                        {
                            Id = 3,
                            EventTitle = "Cultural Day Celebration",
                            Location = "Piazza",
                            TicketPrice = 20m
                        },
                        new
                        {
                            Id = 4,
                            EventTitle = "Career Expo 2026",
                            Location = "Rautenbach Hall",
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            EventTitle = "Intervarsity Rugby Match",
                            Location = "TuksStadium",
                            TicketPrice = 180m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
